services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: app
        ports:
            - "80:80"
        networks:
            - app_redis
    redis:
        image: redis:7-alpine
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - app_redis
networks:
    app_redis:
        name: app-redis